change output

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,8 +28,8 @@ jobs:
           echo "Applying config: ${{ github.event.inputs.custom_config }}"
 
           # Copy from your repo (adjust paths as needed)
-          cp /mnt/shared/${{ github.event.inputs.style_file }} app/utils/Stylesheet.tsx || echo "Style not found"
-          cp /mnt/shared/${{ github.event.inputs.custom_config }} app/utils/config.json || echo "Config not found"
+          cp /mnt/shared/${{ github.event.inputs.output_file }}/${{ github.event.inputs.style_file }} app/utils/Stylesheet.tsx || echo "Style not found"
+          cp /mnt/shared/${{ github.event.inputs.output_file }}/${{ github.event.inputs.custom_config }} app/utils/config.json || echo "Config not found"
       
       # 3. Compile the App
       - name: Build App
@@ -39,4 +39,4 @@ jobs:
       
       - name: Copy App
         run: |
-          cp android/app/build/generated/outputs/bundle/release/app-release.aab /mnt/shared/${{ github.event.inputs.output_file }}
+          cp android/app/build/generated/outputs/bundle/release/app-release.aab /mnt/shared/${{ github.event.inputs.output_file }}/app-release.aab
